Add `disable-O0-optnone` option
arcsysu/SYsU-lang pull request #74
Opened 2023-03-20 13:47 UTC by Huangxt57

By default, `clang` will add the `optnone` attribute to each function, which prevents further optimizations from both built-in pipeline or user custom passes. To avoid this, we can add the `disable-O0-optnone` to `clang`. If not, each transform pass should add a static function [`isRequired`](https://llvm.org/docs/WritingAnLLVMNewPMPass.html#id8) to ensure this pass will be conducted.

2023-03-20 14:20 UTC, wu-kan requested changes
见[这里](https://github.com/llvm/llvm-project/blob/llvmorg-11.0.1/llvm/CMakeLists.txt#L61)，我觉得实验中使用的编程标准应该锚定 LLVM 对应的版本，而实验中使用的 clang-11 默认就是 C++14…

2023-03-20 14:30 UTC, Huangxt57 commented
> 见[这里](https://github.com/llvm/llvm-project/blob/llvmorg-11.0.1/llvm/CMakeLists.txt#L61)，我觉得实验中使用的编程标准应该锚定 LLVM 对应的版本，而实验中使用的 clang-11 默认就是 C++14…

Done.

2023-03-25 10:37 UTC, wu-kan commented
> > 见[这里](https://github.com/llvm/llvm-project/blob/llvmorg-11.0.1/llvm/CMakeLists.txt#L61)，我觉得实验中使用的编程标准应该锚定 LLVM 对应的版本，而实验中使用的 clang-11 默认就是 C++14…
> 
> Done.

关于这一点我其实有一些别的想法想和各位讨论。LLVM 项目使用的默认 C++ 标准实际上恰好就是其编译出的 clang 的默认的版本，例如在最新发布的 LLVM-16 内部使用语言切换到了 C++17，clang-16 默认的 C++ 标准也从 C++14 随着调成了 C++17。如果我们在这个项目里指定了 C++ 版本，那么就意味着我们这个项目可能不能直接配合 LLVM-16 以及以后的版本，日后需要做出调整…

而如果为了实现这个功能（C++使用版本跟随LLVM变化）在 CMakeLists.txt 里面加入一些复杂的逻辑判断，可能又会导致初学者做到这里比较懵逼，是否有更优雅的做法？我的想法是不在 CMakeLists.txt 里指定这个，而是建议做实验的人自己在 cmake 的时候 `-DCMAKE_CXX_STANDARD=14` 或者 `-DCMAKE_CXX_STANDARD=17`，并自己为自己传进去的选项负责。

2023-05-29 12:27 UTC, wu-kan commented
See #113

2023-06-13 14:33 UTC, closed without merging